"""Adaptive report generation.

Renders a :class:`ResearchSession` into a human-readable Markdown report whose
sections *emerge from the available evidence* (``OBJECTIVE.md`` module 10):
a section is rendered only when the session contains material for it, and when
evidence is missing the report says so explicitly instead of padding a
template. The provenance chain is preserved in print: every finding cites the
verified claims behind it, every claim cites its evidence passages and
sources, and every source is listed with its authority assessment. The report
is fully reproducible from the stored session data.
"""
from __future__ import annotations

from research_engine import __version__
from research_engine.domain.models import (
    Claim,
    ResearchReport,
    ResearchSession,
    Source,
    VerificationStatus,
)


class ReportGenerator:
    """Builds a :class:`ResearchReport` from a session."""

    def generate(
        self, session: ResearchSession, executive_summary: str
    ) -> ResearchReport:
        topic = session.request.topic
        source_labels = _source_labels(session.sources)
        claims_by_id = {c.id: c for c in session.claims}

        lines: list[str] = []
        w = lines.append

        w(f"# Research Report: {topic}")
        w("")
        w(f"*Generated by Research Engine v{__version__} — session `{session.id}`*")
        w("")

        self._executive_summary(w, executive_summary)
        self._direct_answer(w, session)
        self._research_plan(w, session)
        self._key_findings(w, session, claims_by_id, source_labels)
        self._verified_claims(w, session, source_labels)
        self._contradictions(w, session, claims_by_id)
        self._uncertainty(w, session)
        self._limitations(w, session)
        self._future_research(w, session)
        self._recommendations(w, session)
        self._appendix(w, session, source_labels)

        markdown = "\n".join(lines)
        return ResearchReport(
            topic=topic,
            executive_summary=executive_summary,
            markdown=markdown,
        )

    # -- sections (each renders only when the session supports it) ----------

    def _executive_summary(self, w, executive_summary: str) -> None:
        w("## Executive Summary")
        w("")
        w(executive_summary or "_No summary available._")
        w("")

    def _direct_answer(self, w, session: ResearchSession) -> None:
        """Rendered only for question-shaped research objectives."""
        if session.plan is None or not session.plan.is_question:
            return
        w("## Direct Answer")
        w("")
        if session.direct_answer:
            w(session.direct_answer)
        else:
            w(
                "_The verified evidence collected in this session was "
                "insufficient to answer the question directly. See Missing "
                "Evidence below._"
            )
        w("")

    def _research_plan(self, w, session: ResearchSession) -> None:
        if session.plan is None:
            return
        plan = session.plan
        w("## Research Plan")
        w("")
        w(f"**Objective:** {plan.objective}")
        w("")
        if plan.scope:
            w(f"**Scope:** {plan.scope}")
            w("")
        if plan.subquestions:
            w("Subquestions investigated:")
            w("")
            for subquestion in plan.subquestions:
                w(f"- ({subquestion.id}) {subquestion.question}")
            w("")
        if plan.exclusion_criteria:
            w(f"**Excluded:** {', '.join(plan.exclusion_criteria)}")
            w("")

    def _key_findings(self, w, session, claims_by_id, source_labels) -> None:
        if not session.findings and not session.patterns:
            return
        w("## Key Findings")
        w("")
        for finding in session.findings:
            citations = _claim_citations(finding.claim_ids)
            w(
                f"- **[{finding.confidence_label} confidence, "
                f"{finding.confidence:.0%}]** {finding.statement} {citations}"
            )
            standing = _finding_standing(finding, claims_by_id, source_labels)
            if standing:
                w(f"  - {standing}")
        if session.patterns:
            w("")
            w("Cross-cutting patterns:")
            w("")
            for pattern in session.patterns:
                w(f"- {pattern}")
        w("")

    def _verified_claims(self, w, session, source_labels) -> None:
        if not session.claims:
            return
        w("## Verified Claims")
        w("")
        w(
            "Each claim lists its type, verification status, and provenance "
            "(evidence passages → sources)."
        )
        w("")
        for claim in session.claims:
            labels = _labels_for(claim.source_ids, source_labels)
            evidence = ", ".join(claim.evidence_ids) or "-"
            w(
                f"- (`{claim.id}`) {claim.text} — *{claim.claim_type.value}*, "
                f"**{claim.status.value}** ({claim.supporting_sources} source(s), "
                f"{claim.independent_domains} domain(s), agreement "
                f"{claim.agreement:.0%}) [evidence: {evidence} → {labels}]"
            )
        w("")

    def _contradictions(self, w, session, claims_by_id) -> None:
        w("## Contradictions")
        w("")
        if session.contradictions:
            for contra in session.contradictions:
                w(f"- {contra.description} (claims: {', '.join(contra.claim_ids)})")
        else:
            w("_No conflicting claims were detected across sources._")
        w("")

    def _uncertainty(self, w, session: ResearchSession) -> None:
        w("## Uncertainty and Confidence")
        w("")
        report = session.confidence
        if report is None:
            w(f"Overall confidence: **{session.overall_confidence:.0%}**.")
            w("")
            return
        w(
            f"Overall confidence: **{report.score:.0%}** ({report.label}). "
            f"{report.explanation}"
        )
        w("")
        w("| Factor | Value |")
        w("| --- | --- |")
        w(f"| Independent sources | {report.independent_sources} |")
        w(f"| Source authority | {report.authority:.0%} |")
        w(f"| Claim agreement | {report.agreement:.0%} |")
        w(f"| Plan coverage | {report.coverage:.0%} |")
        w(f"| Contradictions | {report.contradictions} |")
        w(f"| Evidence quality | {report.evidence_quality:.0%} |")
        w(f"| Claim specificity | {report.specificity:.0%} |")
        w("")
        if session.findings:
            w("Per-finding confidence:")
            w("")
            for finding in session.findings:
                w(
                    f"- {finding.confidence:.0%} ({finding.confidence_label}) — "
                    f"{finding.statement}"
                )
            w("")

    def _limitations(self, w, session: ResearchSession) -> None:
        single_source = sum(
            1
            for c in session.claims
            if c.status is VerificationStatus.SINGLE_SOURCE
        )
        if not session.missing_evidence and not single_source:
            return
        w("## Limitations and Missing Evidence")
        w("")
        for gap in session.missing_evidence:
            w(f"- {gap}")
        if single_source:
            w(
                f"- {single_source} claim(s) rest on a single source and should "
                f"be treated as preliminary."
            )
        w("")

    def _future_research(self, w, session: ResearchSession) -> None:
        if not session.hypotheses and not session.open_questions:
            return
        w("## Future Research")
        w("")
        if session.hypotheses:
            w("Hypotheses worth testing:")
            w("")
            for hyp in session.hypotheses:
                w(f"- **[{hyp.confidence_label}]** {hyp.statement}")
            w("")
        if session.open_questions:
            w("Open questions:")
            w("")
            for question in session.open_questions:
                w(f"- {question}")
            w("")

    def _recommendations(self, w, session: ResearchSession) -> None:
        if not session.suggestions:
            return
        w("## Recommendations")
        w("")
        for suggestion in session.suggestions:
            w(f"- {suggestion}")
        w("")

    def _appendix(self, w, session, source_labels) -> None:
        w("## Appendix")
        w("")
        w("### Retrieval and Verification Statistics")
        w("")
        w(f"- Research-loop iterations: {max(1, session.iterations)}")
        w(f"- Search candidates evaluated: {session.candidates_evaluated}")
        w(
            f"- Candidates rejected before download: "
            f"{session.candidates_rejected}"
        )
        w(f"- Documents downloaded: {session.documents_downloaded}")
        w(f"- Evidence passages extracted: {len(session.evidence)}")
        w(f"- Verified claims: {len(session.claims)}")
        corroborated = sum(
            1 for c in session.claims if c.supporting_sources >= 2
        )
        w(f"- Independently corroborated claims: {corroborated}")
        w("")
        w("### Sources")
        w("")
        if session.sources:
            for source in session.sources:
                label = source_labels.get(source.id, "?")
                authority = (
                    f"{source.authority_tier}, authority {source.authority:.0%}"
                )
                w(
                    f"- [{label}] *{source.title}* — {source.provider} "
                    f"({authority}) (`{source.locator}`)"
                )
        else:
            w("_No sources were downloaded._")
        w("")
        w("### Session Metadata")
        w("")
        w(f"- Session id: `{session.id}`")
        w(f"- Status: {session.status.value}")
        w(f"- Created: {session.created_at}")
        w(f"- Completed: {session.completed_at}")
        for key, value in session.provider_info.items():
            w(f"- {key}: {value}")
        w("")


def _finding_standing(
    finding, claims_by_id: dict[str, Claim], source_labels: dict[str, str]
) -> str:
    """One-line evidential standing for a finding: sources, corroboration, conflicts."""
    claims = [claims_by_id[cid] for cid in finding.claim_ids if cid in claims_by_id]
    if not claims:
        return ""
    source_ids = {sid for c in claims for sid in c.source_ids}
    corroborated = sum(1 for c in claims if c.supporting_sources >= 2)
    conflicted = sum(1 for c in claims if c.contradicts)

    parts: list[str] = []
    labels = _labels_for(sorted(source_ids), source_labels)
    if len(source_ids) >= 2:
        parts.append(f"supported by {len(source_ids)} sources ({labels})")
    else:
        parts.append(f"single-sourced ({labels}); treat as preliminary")
    if corroborated:
        parts.append(f"{corroborated} claim(s) independently corroborated")
    if conflicted:
        parts.append(f"{conflicted} claim(s) contradicted (see Contradictions)")
    parts.append(f"remaining uncertainty ~{1 - finding.confidence:.0%}")
    return "*Evidence: " + "; ".join(parts) + ".*"


def _source_labels(sources: list[Source]) -> dict[str, str]:
    return {source.id: f"S{index}" for index, source in enumerate(sources, start=1)}


def _labels_for(source_ids, source_labels: dict[str, str]) -> str:
    labels = [source_labels.get(sid, "?") for sid in source_ids]
    return ", ".join(labels) if labels else "-"


def _claim_citations(claim_ids: list[str]) -> str:
    if not claim_ids:
        return ""
    shown = ", ".join(f"`{cid}`" for cid in claim_ids[:6])
    more = f", +{len(claim_ids) - 6} more" if len(claim_ids) > 6 else ""
    return f"[{shown}{more}]"
