"""Report generation.

Renders a :class:`ResearchSession` into a human-readable Markdown report while
preserving links from findings to their supporting evidence and sources. The
report is fully reproducible from the stored session data.
"""
from __future__ import annotations

from research_engine import __version__
from research_engine.domain.models import (
    Evidence,
    ResearchReport,
    ResearchSession,
    Source,
)


class ReportGenerator:
    """Builds a :class:`ResearchReport` from a session."""

    def generate(self, session: ResearchSession, executive_summary: str) -> ResearchReport:
        topic = session.request.topic
        source_labels = _source_labels(session.sources)
        evidence_by_id = {e.id: e for e in session.evidence}
        entity_names = {e.id: e.name for e in session.entities}

        lines: list[str] = []
        w = lines.append

        w(f"# Research Report: {topic}")
        w("")
        w(f"*Generated by Research Engine v{__version__} — session `{session.id}`*")
        w("")

        # Executive summary
        w("## Executive Summary")
        w("")
        w(executive_summary or "_No summary available._")
        w("")

        # Research objectives
        w("## Research Objectives")
        w("")
        w(f"Investigate **{topic}** across the following research angles:")
        w("")
        for task in session.tasks:
            if task.kind.value == "collect":
                w(f"- {task.query}")
        w("")

        # Key findings
        w("## Key Findings")
        w("")
        if session.findings:
            for finding in session.findings:
                citations = _evidence_citations(
                    finding.supporting_evidence_ids, evidence_by_id, source_labels
                )
                w(
                    f"- **[{finding.confidence_label} confidence, "
                    f"{finding.confidence:.0%}]** {finding.statement} {citations}"
                )
        else:
            w("_No findings were produced._")
        w("")

        # Supporting evidence
        w("## Supporting Evidence")
        w("")
        if session.evidence:
            for item in session.evidence:
                label = source_labels.get(item.source_id, "?")
                w(f"- ({item.id}) {item.claim} [{label}]")
        else:
            w("_No evidence collected._")
        w("")

        # Extracted entities
        w("## Extracted Entities")
        w("")
        if session.entities:
            for entity in session.entities:
                w(f"- **{entity.name}** ({len(entity.evidence_ids)} mentions)")
        else:
            w("_No entities extracted._")
        w("")

        # Relationships
        w("## Relationships Between Entities")
        w("")
        if session.relationships:
            for rel in session.relationships:
                a = entity_names.get(rel.source_entity_id, rel.source_entity_id)
                b = entity_names.get(rel.target_entity_id, rel.target_entity_id)
                w(f"- {a} — *{rel.relation}* — {b} "
                  f"({len(rel.evidence_ids)} supporting evidence item(s))")
        else:
            w("_No relationships discovered._")
        w("")

        # Hypotheses
        w("## Generated Hypotheses")
        w("")
        if session.hypotheses:
            for hyp in session.hypotheses:
                w(f"- **[{hyp.confidence_label}]** {hyp.statement}")
        else:
            w("_No hypotheses generated._")
        w("")

        # Confidence assessment
        w("## Confidence Assessment")
        w("")
        w(f"Overall confidence: **{session.overall_confidence:.0%}** "
          f"({_label(session.overall_confidence)}).")
        w("")
        if session.findings:
            w("Per-finding confidence:")
            w("")
            for finding in session.findings:
                w(f"- {finding.confidence:.0%} ({finding.confidence_label}) — "
                  f"{finding.statement}")
            w("")

        # Contradictions
        w("## Contradictions and Conflicting Evidence")
        w("")
        if session.contradictions:
            for contra in session.contradictions:
                w(f"- {contra.description}")
        else:
            w("_No conflicting evidence detected._")
        w("")

        # Open questions
        w("## Open Questions")
        w("")
        if session.open_questions:
            for question in session.open_questions:
                w(f"- {question}")
        else:
            w("_None._")
        w("")

        # Suggestions
        w("## Suggestions for Further Investigation")
        w("")
        if session.suggestions:
            for suggestion in session.suggestions:
                w(f"- {suggestion}")
        else:
            w("_None._")
        w("")

        # Citations / references
        w("## Citations and References")
        w("")
        if session.sources:
            for source in session.sources:
                label = source_labels.get(source.id, "?")
                w(f"- [{label}] *{source.title}* — {source.provider} "
                  f"(`{source.locator}`)")
        else:
            w("_No sources._")
        w("")

        # Metadata
        w("## Session Metadata")
        w("")
        w(f"- Session id: `{session.id}`")
        w(f"- Status: {session.status.value}")
        w(f"- Created: {session.created_at}")
        w(f"- Completed: {session.completed_at}")
        for key, value in session.provider_info.items():
            w(f"- {key}: {value}")
        w("")

        markdown = "\n".join(lines)
        return ResearchReport(
            topic=topic,
            executive_summary=executive_summary,
            markdown=markdown,
        )


def _source_labels(sources: list[Source]) -> dict[str, str]:
    return {source.id: f"S{index}" for index, source in enumerate(sources, start=1)}


def _evidence_citations(
    evidence_ids: list[str],
    evidence_by_id: dict[str, Evidence],
    source_labels: dict[str, str],
) -> str:
    labels: list[str] = []
    for eid in evidence_ids:
        item = evidence_by_id.get(eid)
        if item is None:
            continue
        label = source_labels.get(item.source_id)
        if label and label not in labels:
            labels.append(label)
    return f"[{', '.join(labels)}]" if labels else ""


def _label(score: float) -> str:
    from research_engine.domain.models import confidence_label

    return confidence_label(score)
